import { randomUUID } from "crypto";
import path from "path";
import { mkdir, writeFile } from "fs/promises";

// Document files live outside `public/` so they can only ever reach a user
// through the access-checked /api/documents/[id]/download route — never as a
// guessable static URL.
const PRIVATE_UPLOADS_DIR = path.join(process.cwd(), "uploads", "documents");
const PUBLIC_COVERS_DIR = path.join(process.cwd(), "public", "uploads", "covers");
// Chat attachments are public (unlike documents) — anyone with the link can
// view them, same trust model as most chat apps' media hosting. Don't reuse
// this path for anything that needs purchase-gating.
const PUBLIC_CHAT_DIR = path.join(process.cwd(), "public", "uploads", "chat");
const PUBLIC_AVATARS_DIR = path.join(process.cwd(), "public", "uploads", "avatars");
// Course lesson content (video/PDF) — private like documents, served only
// through the enrollment-checked /api/courses/[courseId]/content route.
const PRIVATE_COURSE_DIR = path.join(process.cwd(), "uploads", "courses");

export function extOf(filename: string) {
  return path.extname(filename).toLowerCase();
}

export async function saveDocumentFile(file: File, ext: string) {
  await mkdir(PRIVATE_UPLOADS_DIR, { recursive: true });
  const storageKey = `${randomUUID()}${ext}`;
  const buffer = Buffer.from(await file.arrayBuffer());
  await writeFile(path.join(PRIVATE_UPLOADS_DIR, storageKey), buffer);
  return storageKey;
}

export function resolveDocumentPath(storageKey: string) {
  // storageKey is always a randomUUID()+ext generated by saveDocumentFile,
  // never derived from user input, so there's no path-traversal surface here.
  return path.join(PRIVATE_UPLOADS_DIR, storageKey);
}

export async function saveCoverImage(file: File, ext: string) {
  await mkdir(PUBLIC_COVERS_DIR, { recursive: true });
  const filename = `${randomUUID()}${ext}`;
  const buffer = Buffer.from(await file.arrayBuffer());
  await writeFile(path.join(PUBLIC_COVERS_DIR, filename), buffer);
  return `/uploads/covers/${filename}`;
}

export async function saveChatAttachment(file: File, ext: string) {
  await mkdir(PUBLIC_CHAT_DIR, { recursive: true });
  const filename = `${randomUUID()}${ext}`;
  const buffer = Buffer.from(await file.arrayBuffer());
  await writeFile(path.join(PUBLIC_CHAT_DIR, filename), buffer);
  return `/uploads/chat/${filename}`;
}

export async function saveAvatarFile(file: File, ext: string) {
  await mkdir(PUBLIC_AVATARS_DIR, { recursive: true });
  const filename = `${randomUUID()}${ext}`;
  const buffer = Buffer.from(await file.arrayBuffer());
  await writeFile(path.join(PUBLIC_AVATARS_DIR, filename), buffer);
  return `/uploads/avatars/${filename}`;
}

export async function saveCourseContentFile(file: File, ext: string) {
  await mkdir(PRIVATE_COURSE_DIR, { recursive: true });
  const storageKey = `${randomUUID()}${ext}`;
  const buffer = Buffer.from(await file.arrayBuffer());
  await writeFile(path.join(PRIVATE_COURSE_DIR, storageKey), buffer);
  return storageKey;
}

export function resolveCourseContentPath(storageKey: string) {
  return path.join(PRIVATE_COURSE_DIR, storageKey);
}
